### ISSUE TITLE
Beautify scale slider

### ISSUE THREAD

**Issue by milkyskies** [matchamoon/tsubasa#9]
![image](https://user-images.githubusercontent.com/6336366/170959707-49a72cdd-2651-45d9-9123-4b2d216b7f5f.png)

**Comment by coffeebank** [comment]
Suggestions:
- [ ] Show file resolution
- [ ] Compute factors, to ensure no floats and clean px scaling
  - https://stackoverflow.com/a/43802308/15923512
- [ ] Offer resolution suggestions based on factors, with unchanged resolution as default
- [ ] Advanced mode option that shows slider and custom % box
  - [ ] Custom resolution input with locked aspect ratio (?)
